name: "Composer Validate"

on:
  pull_request: {}
  push:
    branches:
      - 1.x

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: composer validate
